export const listNodes = [
    {   id:null,
        token: 'Block',
        father: null,
        expression: "Block",
        value: null,
        childs: [ ],
    },
    {   id:null,
        token: 'Number',
        father: null,
        expression: "Declarative",
        value: 0,
    },
    {   id:null,
        token:'Variable',
        father: null,
        expression: "Variable",
        value: 0,
        variable: null,
    },
    {   id:null,
        token: 'Assign',
        father: null,
        expression: "Assign",
        value: 0,
        operador: '=',
        childLeft: null,
        childRight: null,
    },
    {   id:null,
        token:'Add',
        father: null,
        expression: 'BinOp',
        value: 0,
        operador:'+',
        childLeft: null,
        childRight: null
    },
    {   id:null,
        token:'Sub',
        father: null,
        expression: 'BinOp',
        value: 0,
        operador: '-',
        childLeft: null,
        childRight: null
    },
    {   id:null,
        token:'Mul',
        father: null,
        expression: 'BinOp',
        value: 0,
        operador: '*',
        childLeft: null,
        childRight: null
    },
    {   id:null,
        token:'Div',
        father: null,
        expression: 'BinOp',
        value: 0,
        operador: '/',
        childLeft: null,
        childRight: null
    },
    { id:null,
      token:'If',
      father: null,
      expression: "If",
      value: null,
      childLeft: null,
      childRight: null,
    },
    {   id:null,
        token: 'For',
        father: null,
        expression: "For",
        value: null,
        childLeft: null,
        childRight: null,
    },
    {   id:null,
        token: 'Print',
        father: null,
        expression: "Print",
        value: '',
    },
  ];

  export const listNodeEditor = [
    {   token: 'Block',
        inputs:1,
        value: {  Value: 0 },
    },
    {   token: 'Number',
        inputs:0,
        value: { Value: 0 },
    },
    {   token: 'Variable',
        inputs:0,
        value: { Variable: '', Value: 0 },
    },
    {   token: 'Assign',
        inputs:2,
        value: { Value: 0 },
    },
    {   token: 'Add',
        inputs:2,
        value: { Value: 0 },
    },
    {   token: 'Sub',
        inputs:2,
        value: { Value: 0 },
    },
    {   token: 'Div',
        inputs:2,
        value: { Value: 0 },
    },
    {   token: 'If',
        inputs:2,
        value: { Operator: '<', Expr1: 0, Expr2: 0 },
    },
    {   token: 'For',
        inputs:1,
        value: { Start: 0, Finish: 0 },
    },
    {   token: 'Print',
        inputs:0,
        value: {  Value: ' ' },
    },
  ];
